version: "3.8"

volumes:
  certs:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_certs
  kibanadata:
    driver: local
  metricbeatdata01:
    driver: local
  filebeatdata01:
    driver: local
  logstashdata01:
    driver: local

networks:
  default:
    name: elastic
    external: false

services:
  metricbeat01:
    image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
    platform: linux/amd64
    extra_hosts:
      - host.docker.internal:host-gateway
    user: root
    volumes:
      - certs:/usr/share/metricbeat/certs
      - metricbeatdata01:/usr/share/metricbeat/data
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
      - KIBANA_HOSTS=${KIBANA_HOSTS}
      - LOGSTASH_HOSTS=http://logstash01:9600
    command:
      - --strict.perms=false

  filebeat01:
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    platform: linux/amd64
    extra_hosts:
      - host.docker.internal:host-gateway
    user: root
    volumes:
      - certs:/usr/share/filebeat/certs
      - filebeatdata01:/usr/share/filebeat/data
      - ./filebeat_ingest_data/:/usr/share/filebeat/ingest_data/
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
      - KIBANA_HOSTS=${KIBANA_HOSTS}
      - LOGSTASH_HOSTS=http://logstash01:9600
      - LOGSTASH_BEATS=logstash01
    command:
      - --strict.perms=false

  logstash01:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    platform: linux/amd64
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      co.elastic.logs/module: logstash
    user: root
    ports:
      - ${LOGSTASH_BEATS_PORT}:${LOGSTASH_BEATS_PORT}
    volumes:
      - certs:/usr/share/logstash/certs
      - logstashdata01:/usr/share/logstash/data
      - ./logstash_ingest_data/:/usr/share/logstash/ingest_data/
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
     # - ./filebeat-pipeline.conf:/usr/share/logstash/pipeline/filebeat-pipeline.conf:ro
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200